[tool.poetry]
name = "django-sage-mailbox"
version = "0.1.3"
description = "A Django package for mailbox client integration."
authors = ["Sepehr Akbarzadeh <sepehr@sageteam.org>"]
readme = "README.md"
license = "MIT"
keywords = ["django", "email", "imap", "mailbox", "sageteam", "django-packages"]
repository = "https://github.com/sageteamorg/django-sage-mailbox"

classifiers=[
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Framework :: Django",
]

packages = [
    { include = "sage_mailbox" }
]

[tool.poetry.urls]
"Documentation" = "https://django-sage-mailbox.readthedocs.io/en/latest/"
"Issues" = "https://github.com/sageteamorg/django-sage-mailbox/issues"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.0.7"
python-sage-imap = "^0.4.2"
django-jsonform = "^2.22.0"
python-dateutil = "^2.9.0.post0"

[tool.poetry.group.dev.dependencies]
black = "^24.4.2"
isort = "^5.13.2"
mypy = "^1.10.1"
pytest = "^8.2.2"
flake8 = "^7.1.0"
tox = "^4.15.1"
coverage = "^7.5.4"
pre-commit = "^3.7.1"
sphinx = "^7.3.7"
pylint = "^3.2.5"
pytest-cov = "^5.0.0"
commitizen = "^3.27.0"
docformatter = "^1.7.5"
types-setuptools = "^70.2.0.20240704"
django-stubs = "^5.0.2"
sphinx-rtd-theme = "^2.0.0"

[tool.black]
line-length = 88
target-version = ['py38']
exclude = '''
/(
    \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | docs
)/
'''

[tool.isort]
profile = "black"
line_length = 88
known_first_party = ["django_sage_mailbox"]
skip = ["docs"]

[tool.mypy]
mypy_path = "stubs"
disallow_untyped_calls = true
disallow_untyped_defs = true
ignore_missing_imports = true
explicit_package_bases = true
exclude = '''
^docs/source/conf.py|
^build/|
^tests/|
^stubs/|
^kernel/
'''

[tool.commitizen]
name = "cz_conventional_commits"
version = "0.1.0"

[tool.pytest.ini_options]
addopts = "--strict-markers"
testpaths = ["tests"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
